name = "SymEngine"
uuid = "123dc426-2d89-5057-bbad-38513e3affd8"
version = "0.7.1"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SymEngine_jll = "3428059b-622b-5399-b16f-d347a77089a4"

[compat]
Compat = "≥ 0.63.0"
RecipesBase = "≥ 0.0.6"
julia = "≥ 1.3.0"
SymEngine_jll = "≥ 0.6.0"
