name = "SymEngine"
uuid = "123dc426-2d89-5057-bbad-38513e3affd8"
version = "0.13.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SymEngine_jll = "3428059b-622b-5399-b16f-d347a77089a4"

[weakdeps]
#SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[extensions]
#SymEngineSymbolicUtilsExt = "SymbolicUtils"
SymEngineTermInterfaceExt = "TermInterface"

[compat]
Compat = "0.63.0, 1, 2, 3, 4"
RecipesBase = "0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 1.0"
SpecialFunctions = "0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 1, 2"
SymEngine_jll = "0.9, 0.10, 0.11, 0.12"
#SymbolicUtils = "3"
TermInterface = "2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
#SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[targets]
test = ["TermInterface", "Test"]
