[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[compat]
Documenter = "1"

[sources]
SymEngine = {path = ".."}
